import { ALL_TASKS, NOT_COMPLETED, COMPLETED } from "./strings"

export const TASK_FILTER_TYPE = {
    ALL: ALL_TASKS,
    NOT_COMPLETED: NOT_COMPLETED,
    COMPLETED: COMPLETED,
}

export const TASK_TYPE_CHOSEN = 'TASK_TYPE_CHOSEN'

